let () =
	let watch = Watchtower.add 5 7 in
	print_endline ("Add 5 7 = " ^ string_of_int watch)
	; let watch = Watchtower.add 7 5 in
	print_endline ("Add 7 5 = " ^ string_of_int watch)
	; let watch = Watchtower.add (-7) 5 in
	print_endline ("Add -7 5 = " ^ string_of_int watch)
	; let watch = Watchtower.add (-31) 5 in
	print_endline ("Add -31 5 = " ^ string_of_int watch)
	; let watch = Watchtower.add 2405 5 in
	print_endline ("Add 2405 5 = " ^ string_of_int watch)
	; let watch = Watchtower.add 2407 5 in
	print_endline ("Add 2407 5 = " ^ string_of_int watch)
	; let watch = Watchtower.sub 5 5 in
	print_endline ("Sub 2407 5 = " ^ string_of_int watch)
	; let watch = Watchtower.sub (-5) 5 in
	print_endline ("Sub -5 5 = " ^ string_of_int watch)
	; let watch = Watchtower.sub 5 (-5) in
	print_endline ("Sub 5 -5 = " ^ string_of_int watch)
