let () =
	print_endline ("toString Spade = " ^ Color.toString Color.Spade)
	; print_endline ("toString Heart = " ^ Color.toString Color.Heart)
	; print_endline ("toString Diamond = " ^ Color.toString Color.Diamond)
	; print_endline ("toString Club = " ^ Color.toString Color.Club)
	; print_endline ("toStringVerbose Spade = " ^   Color.toStringVerbose Color.Spade)
	; print_endline ("toStringVerbose Heart = " ^   Color.toStringVerbose Color.Heart)
	; print_endline ("toStringVerbose Diamond = " ^ Color.toStringVerbose Color.Diamond)
	; print_endline ("toStringVerbose Club = " ^    Color.toStringVerbose Color.Club)
